openapi: 3.0.1
info:
  title: NotesApi
  version: v1
paths:
  /Notes:
    get:
      tags:
        - Notes
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
    post:
      tags:
        - Notes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
          text/json:
            schema:
              $ref: '#/components/schemas/Note'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Note'
      responses:
        '200':
          description: Success
  '/Notes/{category}/{id}':
    get:
      tags:
        - Notes
      parameters:
        - name: category
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Note'
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
            text/json:
              schema:
                $ref: '#/components/schemas/Note'
    delete:
      tags:
        - Notes
      parameters:
        - name: category
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Note'
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
            text/json:
              schema:
                $ref: '#/components/schemas/Note'
components:
  schemas:
    Note:
      type: object
      properties:
        id:
          type: string
          nullable: true
        userId:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        content:
          type: string
          nullable: true
        category:
          type: string
          nullable: true
        created:
          type: string
          nullable: true
        updated:
          type: string
          nullable: true
      additionalProperties: false
